### ISSUE TITLE
[AI]-Bot not canonically called "[AI]-Bot"

### ISSUE THREAD

**Issue by DoerteMitHut** [chris-code/offene-tuer#1]
apparently, the objectively cool name "[AI]-Bot" is not used in code. Pls fix!!!11einself

**Comment by chris-code** [comment]
Dear @DoerteMitHut 

Hopefully the recent set of changes has addressed this issue. The objectively cool name is now used wherever possible. Python's restrictions on valid identifiers precludes some use cases (class- module- and variable names), but it is now used in the title of the main window, the docs, readme and various comments throughout the codebase.
